### ISSUE TITLE
Design and implement panel informing user of actual state of application

### ISSUE THREAD

**Issue by kolszewska** [medtagger/MedTagger#130]
## Expected Behavior

There should be a specific place in user interface that tells user what is the actual state of the application.

## Actual Behavior

For most of the time user is not aware of what state application is in.

**Comment by juliapacula** [comment]
What does it mean? :) Could you explain what state means exactly?

**Comment by Darkoon** [comment]
I think that it will be something along the lines of [status bar](https://en.wikipedia.org/wiki/Status_bar) but without any sophisticated options. Just information about the current state of the app, like `tagging with tool X`, `Selection sent successfully` etc.
