### ISSUE TITLE
Allow users to move view after zooming in

### ISSUE THREAD

**Issue by jpowie01** [medtagger/MedTagger#518]
## Current Behavior

This is probably a bug that was introduced while working on the UI redesign. Users cannot move zoomed-in window view with any sliders or mouse grabbing gesture.

## Expected Behavior

Please bring it back. Ideally, it would be better to introduce "mouse" or "move" tool that will allow users to change currently zoomed-in view.

## Steps to Reproduce the Problem

  1. Go to the labeling page.
  2. Zoom in.
  3. Now, you cannot move zoomed-in view.

## Additional comment

Related PRs: #173, #455.

**Comment by Darkoon** [comment]
Critical bug, fix ASAP.
