### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by roscisz** [medtagger/MedTagger#523]
## Current Behavior

medtagger_backend_database_migrations_1  | Apply database fixtures...
medtagger_backend_database_migrations_1  | [2018-12-08 16:53:43,944][INFO](__main__) - Applying fixtures for user Roles...
medtagger_backend_database_migrations_1  | [2018-12-08 16:53:44,044][INFO](__main__) - Role added for name "admin"
medtagger_backend_database_migrations_1  | [2018-12-08 16:53:44,256][INFO](__main__) - Role added for name "doctor"
medtagger_backend_database_migrations_1  | [2018-12-08 16:53:44,265][INFO](__main__) - Role added for name "volunteer"
medtagger_backend_database_migrations_1  | Configuration synchronization...
medtagger_backend_database_migrations_1  | cp: cannot stat '.example.medtagger.yml': No such file or directory
medtagger_backend_database_migrations_1  | Traceback (most recent call last):
medtagger_backend_database_migrations_1  |   File "scripts/sync_configuration.py", line 195, in <module>
medtagger_backend_database_migrations_1  |     run()
medtagger_backend_database_migrations_1  |   File "scripts/sync_configuration.py", line 187, in run
medtagger_backend_database_migrations_1  |     with open(arguments.configuration) as config_file:
medtagger_backend_database_migrations_1  | IsADirectoryError: [Errno 21] Is a directory: '.medtagger.yml'

## Expected Behavior

Dunno. Medtagger is up and running?

## Steps to Reproduce the Problem

1. git clone https://github.com/jpowie01/MedTagger.git
2. git checkout 38793633ff368fe9f2b4821cf8b3685511a17d58
3. docker-compose up

**Comment by kolszewska** [comment]
Hi, thanks for contacting us. We confirmed that this problems occurs also on our side. We will try to fix it as fast as we can. In the meantime please consider setting up MedTagger either on [Vagrant](https://github.com/jpowie01/MedTagger/blob/master/backend/docs/development_in_vagrant.md) or [native setup](https://github.com/jpowie01/MedTagger/blob/master/backend/docs/development_setup_native.md).

**Comment by kolszewska** [comment]
Hi, sorry for such a long reply. The issue is fixed. There should be no problems with the deployment.
